# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: erkemoz.AutoClicker
PackageVersion: 1.9.5
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{82DB470E-CB83-4F2B-9CC2-A8D3AC17D36A}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/erkemoz-wq/erkemoz-auto-clicker/releases/download/v1.9.5/ErkemozAutoClicker_Kurulum_1.9.5.exe
  InstallerSha256: 1DD1F551A119E72AF3E6C7F8416B0F4CF738B2CEAB81451EF99DCA080521C925
ManifestType: installer
ManifestVersion: 1.9.0
